# Generated by Django 4.2.13 on 2024-05-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad_de_origen', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('historia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('numero', models.IntegerField(null=True)),
                ('habilidad', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
