# Generated by Django 5.0.6 on 2024-05-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad_de_origen', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('historia', models.TextField()),
            ],
        ),
    ]
