# Generated by Django 5.0.6 on 2024-05-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0002_entrenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
